# Generated by Django 5.1.4 on 2025-01-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
