# Generated by Django 5.1.4 on 2025-01-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_review_user_review_email_review_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
