# Generated by Django 5.1.4 on 2025-01-12 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_review_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
